name: Python Poetry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
